# Site settings
title: Mòcheno Technologies
email: mochenotechnologies@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mòcheno Technologies Corporate Website
baseurl: "/arctic-fox-theme" # the subpath of your site, e.g. /blog/
url: "http://diezcami.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: mochenotechnologies

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]